---
# taxonomy: (lambda_humedal, lambda_humedal_urbano, urbano)
environment:
  frog: !!python/tuple [2, 0.1, 0]
  bird: !!python/tuple [2, 1, 0.1]
  dog: !!python/tuple [0, 0.1, 0.5]
  car: !!python/tuple [0, 0, 0.1]
  step: !!python/tuple [0, 0.1, 0.1]
  murmullo: !!python/tuple [0, 0.1, 0.1]
  
  

#taxonomy: (min, max)
min_max:
  frog: [!!python/tuple [2, 4], !!python/tuple [0, 1],!!python/tuple [0, 1]]
  bird: [!!python/tuple [1, 3], !!python/tuple [0, 1],!!python/tuple [0, 1]]
  dog: [!!python/tuple [0, 0], !!python/tuple [0, 1],!!python/tuple [0, 1]]
  car: [!!python/tuple [0, 0], !!python/tuple [0, 0],!!python/tuple [0, 1]]
  step: [!!python/tuple [0, 0], !!python/tuple [0, 1],!!python/tuple [0, 1]]
  murmullo: [!!python/tuple [0, 0], !!python/tuple [0, 1],!!python/tuple [0, 1]]

high_limit:
  frog: 0.5
  bird: !!python/tuple [0.5, 20]
  dog: 0.5
  car: 1.0
  step: 0.5
  murmullo: 1.5

movement:
  frog: false
  bird: false
  dog: false
  car: true
  step: false
  murmullo: true